apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: city-api
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: city-api
  namespace: demo
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: java-gradle
      apps.tanzu.vmware.com/pipeline: test
  source:
    git:
      ref:
        branch: main
      url: https://github.com/making/city-api
